# BSD 2-Clause License
# 
# Copyright (c) 2019, AndreasFagschlunger
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

env:
  global:
    - secure: Ke4VmLfWmK/Ifb24DHFVrprvn4h4qPI7xFWg+u00UY+yW2fnoi+BwNs31OZwc0VwSXQx7Zf/bPVbF6Uh2X++hbRacZbnvXiqR30oH2didUDpIU8C+IPz5lHHzaAVGEPBHmrtkuoDsivHAHvpQ1fA0efuFmbpnCYFyDvkoCOnK8E=
    - secure: ULASz28xodlsbUk6+JUJTkQAdZbTEfixSyDh/APxEBIxQv5mci/RSWnms96SyyNWNmeKV+hk7wYATeAyLJ8B653OVrv9FujYtYNHiyHlOF5QUnOW1QnA25xIzcC23u+sg1OB4m0M/2tyXH3igi272jtHvTL6hiy9TzWBx7VQfGw=
    - secure: TD1T24Chw7a0JveEtMXJuWxej5CZEIa1Yh3I2i4p9uZe1DjqCDWFH00lnESa9/1aZHDj0oTu5WcW/EFo1v9FVtXHeq2QTgQgPHLlHKNfwKjyL6b4OFstBc5WxqGyTu4SNt+LaFAo7nN9UyiE3q6aO/URkPW14qdiTCj09FBaod4=

language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
install: ./gradlew --version
jobs:
  include:
    - stage: Bump version
      if: branch = master
      script: ./deploy.sh bump
    - stage: compile
      script: ./gradlew classes
    - stage: test
      script: ./gradlew test
    - stage: push
      if: branch = master
      script: ./deploy.sh push
    - stage: deploy
      if: branch IN (master, develop)
      script: ./gradlew publish